/**
 * YigYaps Skill Invocation Types
 *
 * Shapes returned by POST /v1/security/invoke/:skillId
 *
 * License: Apache 2.0
 */

/**
 * Per-dimension score returned by the local Rule Engine.
 */
export interface SkillDimensionScore {
  /** Dimension name, e.g. "market_fit" */
  name: string;
  /** Score 0–10 */
  score: number;
  /** Primary conclusion token, e.g. "strong_market_signal" */
  conclusion_key: string;
}

/**
 * Structured evaluation breakdown produced by the local Rule Engine.
 * Present whenever the skill has JSON-formatted rules.
 * null for free-form / lab-preview modes.
 */
export interface SkillEvaluationDetails {
  /** Aggregate score 0–10 */
  overall_score: number;
  /** Aggregate verdict */
  verdict: "recommend" | "neutral" | "caution";
  /** Per-dimension breakdown */
  dimensions: SkillDimensionScore[];
}

/**
 * Invoke mode:
 * - local           — Rules evaluated entirely in-process. Zero external calls.
 * - hybrid          — Local Rule Engine + LLM language polishing (only the
 *                     safe skeleton is transmitted, never rule content).
 * - lab-preview-*   — Author-only preview with raw LLM inference.
 * - mock            — Fallback stub (no knowledge configured).
 */
export type SkillInvokeMode =
  | "local"
  | "hybrid"
  | "lab-preview-expert-key"
  | "lab-preview-platform-key"
  | "mock";

/**
 * Response shape from POST /v1/security/invoke/:skillId
 */
export interface SkillInvokeResult {
  success: boolean;
  /** Natural language conclusion generated by the skill */
  conclusion: string;
  /** Evaluation mode used for this invocation */
  mode: SkillInvokeMode;
  /** Human-readable privacy notice describing what data (if any) left the process */
  privacy_notice: string;
  /** Structured evaluation details — null for free-form / lab-preview responses */
  evaluation_details: SkillEvaluationDetails | null;
}
